{
 "title": "Order API",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dotnet_gc_last_collection_memory_committed_size_bytes{exported_job=\"order-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{exported_job=\"order-api\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum{exported_job=\"order-api\"}[1m])\n/\nrate(http_server_request_duration_seconds_count{exported_job=\"order-api\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", exported_job=\"order-api\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(dotnet_process_cpu_time_seconds_total{exported_job=\"order-api\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}